Add content for kustomize
SUSE/caasp-release-notes pull request #46
Opened 2020-04-21 10:14 UTC by r0ckarong

Still missing more general details what it does and what users should pay attention to. 

Added a note about how to generate the addon configs for an existing cluster after this discussion: 
https://chat.suse.de/channel/caasp-release-coordination?msg=ZqDmtPGAM2dWq7k8T

@ereslibre Can you amend more info on kustomize?
@jordimassaguerpla Please verify that the info I've provided is correct.

Thanks

cc / @kravciak @mjura

2020-04-21 10:21 UTC, mjura requested changes
Only small comment

2020-04-21 10:21 UTC, mjura commented on adoc/MAIN.release-notes.adoc
> +cp /tmp/new-cluster-init/addons CLUSTER-DEFINITION-PATH
I would change it to 
`mv CLUSTER-DEFINITION-PATH/addons CLUSTER-DEFINITION-PATH/addons-old`
`cp -r /tmp/mjura-cluster/addons CLUSTER-DEFINITION-PATH/`

2020-04-21 10:26 UTC, mjura approved these changes
thank you :+1:

2020-04-24 10:33 UTC, jordimassaguerpla commented
Merged in https://github.com/SUSE/caasp-release-notes/pull/47

2020-04-24 10:33 UTC, closed without merging